-- Migration 002: 备注增强、打赏、拍照、加价
ALTER TABLE orders ADD COLUMN tip DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN photo_url TEXT DEFAULT NULL;
ALTER TABLE orders ADD COLUMN extra_charge DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN extra_charge_note VARCHAR(255) DEFAULT NULL;
